#!/bin/bash
while getopts ":mt" opt; do
  case ${opt} in
    m ) # process option m
      echo "Let's make a PACSCRIPT"
      ;;
    t ) # process option t
      ;;
    \? ) echo "Usage: cmd [-h] [-t]"
      ;;
  esac
done
