#!/bin/bash
RED='\033[0;31m'
NC='\033[0m' # No Color
BLUE='\033[1;34m'
while getopts ":mt" opt; do
  case ${opt} in
    m ) # process option m
      echo "Let's make a PACSCRIPT"
      echo "$(curl https://raw.githubusercontent.com/Henryws/pacstall/1.0.4-Celeste/misc/APP)" > /tmp/PACSCRIPTtmp
      ;;
    t ) # process option t
      ;;
    \? ) echo "Usage: cmd [-h] [-t]"
      ;;
  esac
done
